### ISSUE TITLE
Suggestion: Allow day/night durations greater than 18000 ticks

### ISSUE THREAD

**Issue by ThePatmann** [AnodeCathode/Time4TFC#1]
Hello, I am developing an expert style pack in TFC and am using this mod. I was planning on doubling the duration of day and night. However I can't go past 1.5x with the current way the configuration is designed.

**Comment by AnodeCathode** [comment]
Changing the length of the day will cause issues with TFC and I've no interest in altering the mod to attempt it. Feel free to fork it and do it yourself if you think that it's not going to cause issues.
